FROM ubuntu:18.04
MAINTAINER Mike Jenner

RUN apt update && apt install --yes \
	build-essential	\
    vim \
    python3 \
    nmap \    
    python-pip \
    htop 


RUN apt upgrade --yes


RUN echo "set -o vi" >> /root/.bashrc
RUN echo "source .bashrc" >> /root/.bash_profile


# following copied in for txblaster

RUN apt update && apt install -y \
    curl \
    unzip \
    libcrypto++6 \
    libboost-all-dev

RUN curl https://rea.crea.si/download/nchain/gateway/TxBlaster6_2.zip -O

RUN unzip TxBlaster6_2.zip

RUN chmod +x TxBlaster6/bin/ubuntu18/TxBlaster

EXPOSE 8332 18332 18444




